/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaCobro;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Yamir Garcia
 */
public class Alta_Usuarios extends javax.swing.JFrame {
    
    boolean estado = false;
    ConexionSQL conexion = new ConexionSQL();
    PreparedStatement st;
    ResultSet rs;
    Statement stt;
    Connection conn;

    /**
     * Creates new form Alta_Usuarios
     */
    public Alta_Usuarios() {
        initComponents();
        verifica_campos();
        error_usuario.setVisible(false);
        error_psw.setVisible(false);
        error_vpsw.setVisible(false);
        error_tipo.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Selector_Acceso = new javax.swing.JComboBox<>();
        Usuario = new javax.swing.JTextField();
        psw = new javax.swing.JTextField();
        Vpsw = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_Agregar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        error_tipo = new javax.swing.JLabel();
        error_usuario = new javax.swing.JLabel();
        error_psw = new javax.swing.JLabel();
        error_vpsw = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Selector_Acceso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Administrador", "Gestor" }));
        Selector_Acceso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                Selector_AccesoItemStateChanged(evt);
            }
        });

        Usuario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                UsuarioFocusLost(evt);
            }
        });
        Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuarioActionPerformed(evt);
            }
        });
        Usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UsuarioKeyReleased(evt);
            }
        });

        psw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pswKeyReleased(evt);
            }
        });

        Vpsw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                VpswKeyReleased(evt);
            }
        });

        jLabel1.setText("Usuario");

        jLabel2.setText("Contraseña");

        jLabel3.setText("Verifica Contraseña");

        jLabel4.setText("Tipo de Usario");

        btn_Agregar.setText("Agregar");
        btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AgregarActionPerformed(evt);
            }
        });

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        error_tipo.setForeground(new java.awt.Color(255, 0, 0));
        error_tipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error_tipo.setText("Escoga un tipo de usuario");

        error_usuario.setForeground(new java.awt.Color(255, 0, 0));
        error_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error_usuario.setText("Este usario ya existe");

        error_psw.setForeground(new java.awt.Color(255, 0, 0));
        error_psw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error_psw.setText("Las contraseñas no coinciden");

        error_vpsw.setForeground(new java.awt.Color(255, 0, 0));
        error_vpsw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        error_vpsw.setText("Las contraseñas no coinciden");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(error_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(error_psw, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(psw, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Vpsw, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(error_vpsw, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Selector_Acceso, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(error_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btn_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(btn_Agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(error_usuario))
                    .addComponent(Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(error_psw))
                    .addComponent(psw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Vpsw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(error_vpsw)))
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addGap(13, 13, 13)
                .addComponent(Selector_Acceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(error_tipo)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Cancelar)
                    .addComponent(btn_Agregar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuarioActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        Usuarios obj = new Usuarios();
        obj.setTitle("Alta de Usuarios");
        obj.setLocationRelativeTo(null);
        this.dispose();
        obj.setVisible(true);

    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AgregarActionPerformed
        String Selector = String.valueOf(Selector_Acceso.getSelectedItem());
        if (!Selector.equalsIgnoreCase("-")) {
            error_tipo.setVisible(false);
            if (psw.getText().equals(Vpsw.getText())) {
                error_psw.setVisible(false);
                error_vpsw.setVisible(false);
                valida_usuario();
                if (!estado) {
                    error_usuario.setVisible(false);
                    try {
                        conn = ConexionSQL.conectar();
                        String sentencia = "INSERT INTO USUARIO (Nombre, Nivel_Acceso, pasword, estado) values (?,?,?,?);";
                        st = conn.prepareStatement(sentencia);
                        st.setString(1, Usuario.getText());
                        st.setString(2, Selector);
                        st.setString(3, psw.getText());
                        st.setString(4, "Activo");
                        int res = st.executeUpdate();
                        if (res > 0) {
                            Usuarios obj = new Usuarios();
                            obj.setTitle("Alta de Usuarios");
                            obj.setLocationRelativeTo(null);
                            this.dispose();
                            JOptionPane.showMessageDialog(null, "Se ha registrado con éxito", "Exito!", JOptionPane.INFORMATION_MESSAGE);
                            obj.setVisible(true);
                            
                        } else {
                            JOptionPane.showMessageDialog(null, "Ups! Algo salio mal", "Error!", JOptionPane.ERROR_MESSAGE);
                        }
                        st.close();
                    } catch (SQLException e) {
                        System.out.println(e);
                        JOptionPane.showMessageDialog(null, "Ups! Algo salio mal", "Error!", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    error_usuario.setVisible(true);
                }
                
            } else {
                error_psw.setVisible(true);
                error_vpsw.setVisible(true);
            }
        } else {
            error_tipo.setVisible(true);
            if (psw.getText().equals(Vpsw.getText())) {
                error_psw.setVisible(false);
                error_vpsw.setVisible(false);                
            } else {
                error_psw.setVisible(true);
                error_vpsw.setVisible(true);
            }
            valida_usuario();
            if (estado) {
                error_usuario.setVisible(false);
            } else {
                error_usuario.setVisible(true);
            }
        }
        

    }//GEN-LAST:event_btn_AgregarActionPerformed

    private void UsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UsuarioKeyReleased
        verifica_campos();
    }//GEN-LAST:event_UsuarioKeyReleased

    private void pswKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pswKeyReleased
        verifica_campos();
    }//GEN-LAST:event_pswKeyReleased

    private void VpswKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VpswKeyReleased
        verifica_campos();
    }//GEN-LAST:event_VpswKeyReleased

    private void Selector_AccesoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_Selector_AccesoItemStateChanged
        verifica_campos();
    }//GEN-LAST:event_Selector_AccesoItemStateChanged

    private void UsuarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_UsuarioFocusLost
        valida_usuario();
    }//GEN-LAST:event_UsuarioFocusLost

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Selector_Acceso;
    private javax.swing.JTextField Usuario;
    private javax.swing.JTextField Vpsw;
    private javax.swing.JButton btn_Agregar;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JLabel error_psw;
    private javax.swing.JLabel error_tipo;
    private javax.swing.JLabel error_usuario;
    private javax.swing.JLabel error_vpsw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField psw;
    // End of variables declaration//GEN-END:variables

    public void verifica_campos() {
        String Selector = String.valueOf(Selector_Acceso.getSelectedItem());
        if (Usuario.getText().equalsIgnoreCase("") || psw.getText().equalsIgnoreCase("") || Vpsw.getText().equalsIgnoreCase("") || Selector.equalsIgnoreCase("-")) {
            btn_Agregar.setEnabled(false);
        } else {
            btn_Agregar.setEnabled(true);
        }
    }
    
    public void valida_usuario() {
        estado = false;
        conn = ConexionSQL.conectar();
        String sentencia = "SELECT Nombre from Usuario";
        try {
            st = conn.prepareStatement(sentencia);
            rs = st.executeQuery();
            if (rs.next()) {
                do {
                    if (rs.getString("Nombre").equals(Usuario.getText())) {
                        btn_Agregar.setEnabled(false);
                        error_usuario.setVisible(true);
                        estado = true;
                        break;
                    }
                } while (rs.next());
                if (!estado) {
                    error_usuario.setVisible(false);
                    verifica_campos();
                }
            } else {
                error_usuario.setVisible(false);
                verifica_campos();
                
            }
            st.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
    
}
