/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaCobro;

/**
 *
 * @author LEVEN
 */
public class Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Consultas
     */
    public Consultas() {
        initComponents();
        PanBuscar.setVisible(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngConsultas = new javax.swing.ButtonGroup();
        btnConsultar = new javax.swing.JButton();
        PanBuscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNoControl = new javax.swing.JTextField();
        rbtnEmail = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbtnTodas = new javax.swing.JRadioButton();
        rbtnTelEmergencia = new javax.swing.JRadioButton();
        rbtnRFC = new javax.swing.JRadioButton();
        rbtnCurp = new javax.swing.JRadioButton();
        rbtnDireccion = new javax.swing.JRadioButton();
        rbtnFecha = new javax.swing.JRadioButton();
        rbtnConsulta = new javax.swing.JRadioButton();
        rbtnBuscar = new javax.swing.JRadioButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("No. de control/Nombre");

        txtNoControl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoControlActionPerformed(evt);
            }
        });

        rbtnEmail.setText("E-mail");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Datos:");

        rbtnTodas.setText("Todas");
        rbtnTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTodasActionPerformed(evt);
            }
        });

        rbtnTelEmergencia.setText("Telefono de Emergencia");

        rbtnRFC.setText("RFC");

        rbtnCurp.setText("CURP");

        rbtnDireccion.setText("Direccion");

        rbtnFecha.setText("Fecha de inscripcion");

        javax.swing.GroupLayout PanBuscarLayout = new javax.swing.GroupLayout(PanBuscar);
        PanBuscar.setLayout(PanBuscarLayout);
        PanBuscarLayout.setHorizontalGroup(
            PanBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanBuscarLayout.createSequentialGroup()
                .addGroup(PanBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanBuscarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72)
                        .addComponent(txtNoControl, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanBuscarLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(PanBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnTodas)
                            .addComponent(jLabel3)
                            .addGroup(PanBuscarLayout.createSequentialGroup()
                                .addGroup(PanBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnEmail)
                                    .addComponent(rbtnRFC)
                                    .addComponent(rbtnDireccion))
                                .addGap(99, 99, 99)
                                .addGroup(PanBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbtnFecha)
                                    .addComponent(rbtnCurp)
                                    .addComponent(rbtnTelEmergencia))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanBuscarLayout.setVerticalGroup(
            PanBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNoControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanBuscarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbtnTodas)
                        .addGap(14, 14, 14)
                        .addGroup(PanBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnEmail)
                            .addComponent(rbtnTelEmergencia))
                        .addGap(18, 18, 18)
                        .addGroup(PanBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtnRFC)
                            .addComponent(rbtnCurp))
                        .addGap(18, 18, 18)
                        .addComponent(rbtnDireccion)
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanBuscarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbtnFecha)
                        .addContainerGap())))
        );

        btngConsultas.add(rbtnConsulta);
        rbtnConsulta.setText("Consultar Deudores");
        rbtnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnConsultaActionPerformed(evt);
            }
        });

        btngConsultas.add(rbtnBuscar);
        rbtnBuscar.setText("Buscar alumno");
        rbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnBuscarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(rbtnBuscar)
                .addGap(81, 81, 81)
                .addComponent(rbtnConsulta)
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsultar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnConsulta)
                    .addComponent(rbtnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(PanBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNoControlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoControlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoControlActionPerformed

    private void rbtnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnConsultaActionPerformed
        if(rbtnConsulta.isSelected()){
            PanBuscar.setVisible(false);
        }
    }//GEN-LAST:event_rbtnConsultaActionPerformed

    private void rbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnBuscarActionPerformed
        if(rbtnBuscar.isSelected()){
         PanBuscar.setVisible(true);
        }
        else{
            PanBuscar.setVisible(false);
        }
    }//GEN-LAST:event_rbtnBuscarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        if(rbtnConsulta.isSelected()){
            Deudores ded = new Deudores();
            ded.setTitle("Deudores");
            ded.setLocationRelativeTo(null);
            ded.setVisible(true);
            this.setVisible(false);
        }
        else if(rbtnBuscar.isSelected()){
            Alumno al = new Alumno();
            al.setTitle("informacion de "+ txtNoControl.getText());
            al.setLocationRelativeTo(null);
            al.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void rbtnTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTodasActionPerformed
        if(rbtnTodas.isSelected()){
            rbtnEmail.setSelected(true);
            rbtnTelEmergencia.setSelected(true);
            rbtnRFC.setSelected(true);
            rbtnCurp.setSelected(true);
            rbtnDireccion.setSelected(true);
            rbtnFecha.setSelected(true);
        }
        else{
            rbtnEmail.setSelected(false);
            rbtnTelEmergencia.setSelected(false);
            rbtnRFC.setSelected(false);
            rbtnCurp.setSelected(false);
            rbtnDireccion.setSelected(false);
            rbtnFecha.setSelected(false);
        }
    }//GEN-LAST:event_rbtnTodasActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.ButtonGroup btngConsultas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rbtnBuscar;
    private javax.swing.JRadioButton rbtnConsulta;
    private javax.swing.JRadioButton rbtnCurp;
    private javax.swing.JRadioButton rbtnDireccion;
    private javax.swing.JRadioButton rbtnEmail;
    private javax.swing.JRadioButton rbtnFecha;
    private javax.swing.JRadioButton rbtnRFC;
    private javax.swing.JRadioButton rbtnTelEmergencia;
    private javax.swing.JRadioButton rbtnTodas;
    private javax.swing.JTextField txtNoControl;
    // End of variables declaration//GEN-END:variables

}
