/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemaCobro;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author LEVEN
 */
public class RegistrarDeuda extends javax.swing.JFrame {

    ConexionSQL conexion = new ConexionSQL();
    PreparedStatement st;
    Statement stt;
    ResultSet rs;
    Connection conn;

    /**
     * Creates new form NewJFrame
     */
    public RegistrarDeuda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Monto_Pago = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Nombre_Alumno = new javax.swing.JTextField();
        Concepto_Pago = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Monto:");

        jLabel3.setText("Concepto:");

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("No. Control");

        Concepto_Pago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libro", "Insripción", "Mensualidad", "Certificación" }));
        Concepto_Pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Concepto_PagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre_Alumno)
                            .addComponent(Monto_Pago)
                            .addComponent(Concepto_Pago, 0, 190, Short.MAX_VALUE))))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Nombre_Alumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Monto_Pago, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Concepto_Pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnCancelar))
                .addGap(75, 75, 75))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void Concepto_PagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Concepto_PagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Concepto_PagoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String motivo = String.valueOf(Concepto_Pago.getSelectedItem());
        if (!Nombre_Alumno.getText().isEmpty() && !Monto_Pago.getText().isEmpty()) {
            try {
                conn = ConexionSQL.conectar();
                //hacemos una consulta para ver si el alumno tiene deuda y si tiene deuda en este concepto
                String sentencia = "select " + motivo + " ,Saldo from DEUDA where ALUMNO_NumeroControl = " + Nombre_Alumno.getText();
                rs = st.executeQuery(sentencia);
                //Verificamos si arroja un resultado
                if (rs.next()) {
                    double total = rs.getDouble(1) + Double.valueOf(Monto_Pago.getText()) - rs.getDouble(2);
                    //Revisamos si con el saldo a favor que tenia paga la deuda
                    //Si el resultado es negativo, solo actualizamos el valor de Slado al slado restante
                    if (total < 0) {
                        total = total * (-1);
                        sentencia = "UPDATE DEUDA set Saldo = " + total + " where ALUMNO_NumeroControl = " + Nombre_Alumno.getText();
                        stt.executeQuery(sentencia);
                    } //Si el total es positivo signifca que el saldo a favor no era suficiente, por que se debe poner en cero el saldo
                    //y poner la deuda restante en el concepto correponidente
                    else {
                        sentencia = "UPDATE DEUDA set " + motivo + " = " + total + " ,Saldo = 0.0 where ALUMNO_NumeroControl = " + Nombre_Alumno.getText();
                        stt.executeQuery(sentencia);
                    }

                } else {
                    //Si este alumno no ha tenido una deuda se crea su registro
                    sentencia = "Insert into DEUDA (ALUMNO_NumeroControl,Libro,Inscripcion,Mensualidad,Certificacion,Saldo) values (?,?,?,?,?,?)";
                    st = conn.prepareStatement(sentencia);
                    switch (motivo) {
                        case "Libro":
                            st.setInt(1, Integer.parseInt(Nombre_Alumno.getText()));
                            st.setDouble(2, Double.valueOf(Monto_Pago.getText()));
                            st.setDouble(3, 0.0);
                            st.setDouble(4, 0.0);
                            st.setDouble(5, 0.0);
                            st.setDouble(6, 0.0);
                            break;
                        case "Insripción":
                            st.setInt(1, Integer.parseInt(Nombre_Alumno.getText()));
                            st.setDouble(2, 0.0);
                            st.setDouble(3, Double.valueOf(Monto_Pago.getText()));
                            st.setDouble(4, 0.0);
                            st.setDouble(5, 0.0);
                            st.setDouble(6, 0.0);
                            break;
                        case "Mensualidad":
                            st.setInt(1, Integer.parseInt(Nombre_Alumno.getText()));
                            st.setDouble(2, 0.0);
                            st.setDouble(3, 0.0);
                            st.setDouble(4, Double.valueOf(Monto_Pago.getText()));
                            st.setDouble(5, 0.0);
                            st.setDouble(6, 0.0);
                            break;
                        case "Certificación":
                            st.setInt(1, Integer.parseInt(Nombre_Alumno.getText()));
                            st.setDouble(2, 0.0);
                            st.setDouble(3, 0.0);
                            st.setDouble(4, 0.0);
                            st.setDouble(5, Double.valueOf(Monto_Pago.getText()));
                            st.setDouble(6, 0.0);
                            break;
                    }
                }
                int res = st.executeUpdate();
                if (res > 0) {
                    JOptionPane.showMessageDialog(null, "Se ha registrado con éxito");
                } else {
                    JOptionPane.showMessageDialog(null, "Ups! Algo salio mal");
                }
                st.close();
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Revise que todos los campos esten llenos");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Concepto_Pago;
    private javax.swing.JTextField Monto_Pago;
    private javax.swing.JTextField Nombre_Alumno;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
